homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Singapore

  customize: !include includes/customize_me.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret ui_http_pi_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:


media_player:
  - platform: sonos

  - platform: braviatv
    host: !secret android_tv_ip
    name: TV

notify:
  - platform: nfandroidtv
    name: LivingTv
    host: !secret android_tv_ip
    interrupt: 1
    transparency: 50%
    position: bottom-right


# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Text to speech
tts:
  - platform: google
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 20000

remote:
  - platform: harmony
    name: living room
    host: !secret remote_host



zwave:
 usb_path: /dev/ttyACM0
 config_path: !secret zwave_config_path

emulated_hue:
   host_ip: !secret emul_hue_host_ip
   listen_port: 80
   off_maps_to_on_domains:
     - script
     - scene
   expose_by_default: true
   exposed_domains:
     - light
     - switch


logger:
  default: info

recorder:
  db_url: !secret mysql_url
  purge_days: 5


device_tracker:
  - platform: !secret dev_tracker_platform
    host: !secret dev_tracker_host
    username: !secret dev_tracker_username
    password: !secret dev_tracker_password
    interval_seconds: 10
    consider_home: 180
    track_new_devices: yes

  - platform: owntracks


proximity:
  home:
    ignored_zones:
      - Work
    devices:
      - device_tracker.dima_i7phone
    tolerance: 50
    unit_of_measurement: km

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'ALARM'
        actions:
          - identifier: TEST_ALARM
            title: 'Test Alarm'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_broker_port
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

input_boolean: !include includes/input_boolean.yaml
automation: !include includes/automations/automation.yaml
group: !include groups.yaml

script: !include scripts.yaml


sensor: !include_dir_merge_list includes/sensors

zone:  !include includes/zone.yaml

