homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Asia/Singapore

  # Customization file
  #customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

hassio:

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret ui_http_pi_password
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

media_player:

  - platform: braviatv
    host: !secret android_tv_ip
    name: TV

notify:
  - platform: nfandroidtv
    name: LivingTv
    host: !secret android_tv_ip
    interrupt: 1
    transparency: 50%
    position: bottom-right

  - platform: facebook
    name: facebook_wind_alerts
    page_access_token: !secret facebook_page_access_token


# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
    language: en
    cache: true
    cache_dir: /tmp/tts
    time_memory: 20000

  - platform: yandextts
    name: yandextts
    api_key: !secret yandex_api_key
    voice: oksana
    speed: 0.8
    emotion: good
    lang: en-US


remote:
  - platform: harmony
    name: livingroom
    host: !secret harmony_living

  - platform: harmony
    name: bedroom
    host: !secret harmony_bedroom


zwave:
  usb_path: /dev/ttyACM0

emulated_hue:
   host_ip: !secret emul_hue_host_ip
   listen_port: 80
   off_maps_to_on_domains:
     - script
     - scene
   expose_by_default: true
   exposed_domains:
     - light
     - switch

#august:
#  login_method: phone
#  username: !secret user1_phone
#  password: !secret august_password
#  timeout: 20

asuswrt:
   host: !secret dev_tracker_host
   username: !secret dev_tracker_username
   ssh_key:  /config/ssh/id_rsa
   protocol: ssh


#  - platform: owntracks

proximity:
  home:
    ignored_zones:
      - Work
    devices:
      - device_tracker.dima_dmitry
    tolerance: 50
    unit_of_measurement: km

ios:
  push:
    categories:
      - name: Alarm
        identifier: 'TEST_ALARM'
        actions:
          - identifier: TEST_ALARM
            title: 'HA Message'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_broker_port
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

camera:
  - platform: !secret camera_type
    ip: !secret camera_ip
    username: !secret camera_login
    password: !secret camera_password

recorder:
  db_url: !secret mdb_url
  purge_interval: 2
  purge_keep_days: 7

logger:
  default: info
  logs:
    homeassistant.components.notify: debug



sensor: !include_dir_merge_list includes/sensors
zone:  !include includes/zone.yaml
input_boolean: !include includes/input_boolean.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
