- alias: 'Dexter Pee call'
  trigger:
    platform: mqtt
    topic: iot/button/dexter/pee
  action:
    service: notify.ios_i7phone
    data:
      message: 'Daddy. I want to go pee.'
      data:
        push:
          badge: 5
          category: TEST_ALARM

- alias: 'Test TV Notification'
  trigger:
    platform: state
    entity_id: device_tracker.iphone
    from: 'someplace'
    to: 'someplace'
  action:
    service: notify.LivingTv
    data:
      title: "Wind Alert"
      message: "It's Windy!"

- alias: ET Comes Home
  trigger:
      platform: state
      entity_id: device_tracker.iphone
      from: 'not_home'
      to: 'home'
  action:
     service: notify.ios_i7phone
     data:
       message: 'ET is home'
       data:
         push:
           badge: 5
           category: TEST_ALARM

- alias: ET Left Home
  trigger:
      platform: state
      entity_id: device_tracker.iphone
      from: 'home'
      to: 'not_home'
  action:
     service: notify.ios_i7phone
     data:
       message: 'ET left home'
       data:
         push:
           badge: 5
           category: TEST_ALARM


- alias: Cleaner Arrives
  trigger:
      platform: state
      entity_id: device_tracker.galaxynote5
      from: 'not_home'
      to: 'home'
  action:
     service: notify.ios_i7phone
     data:
       message: 'Cleaner Arrived'
       data:
         push:
           badge: 5
           category: TEST_ALARM

- alias: Cleaner Left
  trigger:
      platform: state
      entity_id: device_tracker.galaxynote5
      from: 'home'
      to: 'not_home'
  action:
      service: notify.ios_i7phone
      data:
        message: 'Cleaner Left Home'
        data:
          push:
            badge: 5
            category: TEST_ALARM

- alias: Dog Walker Arrived
  trigger:
    platform: state
    entity_id: device_tracker.prioskasiphone
    from: 'not_home'
    to: 'home'
  action:
    service: notify.ios_i7phone
    data:
      message: 'Dog Wallker Arrived'
      data:
        push:
          badge: 5
          category: TEST_ALARM

- alias: Dog Walker Left Home
  trigger:
    platform: state
    entity_id: device_tracker.prioskasiphone
    from: 'home'
    to: 'not_home'
  action:
    service: notify.ios_i7phone
    data:
      message: 'Dog Walker left house recently'
      data:
        push:
          badge: 5
          category: TEST_ALARM


- alias: Aircon ON
  trigger:
    platform: state
    entity_id: input_boolean.aircon
    to: 'on'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: Power ON
      device: !secret au_device_id_aircon

- alias: Bedroom Aircon ON
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_aircon
    to: 'on'
  action:
      service: script.turn_bedroom_aircon_on

- alias: Bedroom Aircon OFF
  trigger:
    platform: state
    entity_id: input_boolean.bedroom_aircon
    to: 'off'
  action:
    service: climate.set_operation_mode
    entity_id: climate.bedroom_climate_control_cooling_1
    data:
      operation_mode: "Off"


- alias: Office Aircon ON
  trigger:
    platform: state
    entity_id: input_boolean.office_aircon
    to: 'on'
  action:
    service: script.turn_office_aircon_on

- alias: Office Dehumidifier ON
  trigger:
    platform: state
    entity_id: input_boolean.office_dehumidifer
    to: 'on'
  action:
    service: script.turn_office_dehumidifier_on


- alias: Office Aircon OFF
  trigger:
    platform: state
    entity_id: input_boolean.office_aircon
    to: 'off'
  action:
    service: climate.set_operation_mode
    entity_id: climate.office_climate_control_cooling_1
    data:
      operation_mode: "Off"

- alias: Office Dehumidifier OFF
  trigger:
    platform: state
    entity_id: input_boolean.office_dehumidifer
    to: 'off'
  action:
    service: script.turn_office_dehumidifier_off

- alias: Guestroom Aircon ON
  trigger:
    platform: state
    entity_id: input_boolean.guestroom_aircon
    to: 'on'
  action:
      service: script.turn_guestroom_aircon_on

- alias: Guestroom Aircon OFF
  trigger:
    platform: state
    entity_id: input_boolean.guestroom_aircon
    to: 'off'
  action:
    service: climate.set_operation_mode
    entity_id: climate.guestroom_climate_control_cooling_1
    data:
      operation_mode: "Off"


- alias: Aircon OFF
  trigger:
    platform: state
    entity_id: input_boolean.aircon
    to: 'off'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: Power OFF
      device: !secret au_device_id_aircon


- alias: Fan ON
  trigger:
    platform: state
    entity_id: input_boolean.fan
    to: 'on'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: PowerToggle
      device: !secret au_device_id_fan


- alias: Fan OFF
  trigger:
    platform: state
    entity_id: input_boolean.fan
    to: 'off'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: PowerToggle
      device: !secret au_device_id_fan

- alias: Tv ON
  trigger:
    platform: state
    entity_id: input_boolean.tv
    to: 'on'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: PowerOn
      device: !secret au_device_id_tv


- alias: Tv OFF
  trigger:
    platform: state
    entity_id: input_boolean.tv
    to: 'off'
  action:
    service: remote.send_command
    data_template:
      entity_id: remote.living_room
      command: PowerOff
      device: !secret au_device_id_tv


- alias: Door Entry
  trigger:
    platform: state
    entity_id: sensor.living_room_door_entry
    to: 'Open'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
      #to: 'below_horizon'
  action:
    service: script.turn_living_room_lights_on


- alias: Living Room Lights ON
  trigger:
    platform: state
    entity_id: sensor.living_room_motion
    to: 'Burglar'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        #to: 'below_horizon'
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.motion_detection
        #to: 'on'
        state: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: light.living_room_ceiling_light_1_level

- alias: Turn off Living room lights after 10 mins no motion
  trigger:
    platform: state
    entity_id: sensor.living_room_motion
    to: 'Off'
    for:
      minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.motion_detection
        state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.living_room_ceiling_light_1_switch

- alias: BedRoom Lights ON
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion
    to: 'Burglar'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.motion_detection
        state: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: switch.bedroom_ceiling_light_switch

- alias: Turn off Bedroom room lights after 2 mins no motion
  trigger:
    platform: state
    entity_id: sensor.bedroom_motion
    to: 'Off'
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.motion_detection
        #to: 'on'
        state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.bedroom_ceiling_light_switch


