
- platform: yr

- platform: template
  sensors:
    living_room_motion:
        friendly_name: 'Living Room Motion'
        value_template: >-
          {%- if is_state("sensor.living_room_door_burglar_4_10", "8") -%}
            Burglar 
          {%- else -%}
            Off 
          {%- endif -%}

    living_room_door_entry:
        friendly_name: 'Living Room Door'
        value_template: >-
          {%- if is_state("sensor.living_room_door_access_control_4_9", "23") -%}
            Closed
          {%- elif is_state("sensor.living_room_door_access_control_4_9", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

    living_room_luminance:
        friendly_name: 'Living Room Luminance'
        value_template: >-
          {%- if is_state("sensor.living_room_door_luminance_4_3", "2") -%}
            Dark 
          {%- else -%}
            Off 
          {%- endif -%}
