- platform: wunderground
  friendly_name: Costa Wind
  api_key: !secret wunder_api_key
  pws_id: !secret  wunder_station_costa_id
  monitored_conditions:
    - wind_kph
    - wind_dir
    - wind_gust_kph
    - pressure_trend
    - wind_string
    - weather_1h

- platform: wunderground
  friendly_name: NCS Wind
  api_key: !secret wunder_api_key
  pws_id: !secret  wunder_station_n_sail_id
  monitored_conditions:
    - wind_kph
    - wind_dir
    - wind_gust_kph



- platform: sql
  db_url: !secret mdb_url
  queries:
    - name: avg_wnd
      query: 'select avg(state) as avr_wind_20m from states where  entity_id = "sensor.pws_wind_kph" and state != "0" and created >= ADDDATE( UTC_TIMESTAMP(), INTERVAL -20 minute) group by entity_id'
      column: 'avr_wind_20m'
      unit_of_measurement: kph

    - name: avg_wnd_gust
      query: 'select avg(state) as avr_wind_gust_20m from states where  entity_id = "sensor.pws_wind_gust_kph" and state != "0" and created >= ADDDATE( UTC_TIMESTAMP(), INTERVAL -20 minute) group by entity_id'
      column: 'avr_wind_gust_20m'
      unit_of_measurement: kph



- platform: template
  sensors:


    nscwindgust:
        friendly_name: 'NSC Gust'
        icon_template: mdi:weather-windy
        unit_of_measurement: 'kmh'
        value_template:  "{{ states.sensor.pws_wind_gust_kph_2.state | float  }}"

    nscwind:
        friendly_name: 'NSC Wind'
        icon_template: mdi:weather-windy
        unit_of_measurement: 'kmh'
        value_template:  "{{ states.sensor.pws_wind_kph_2.state | float  }}"

    nscwindtotal:
        friendly_name: 'NSC Wind Total'
        icon_template: mdi:weather-windy
        unit_of_measurement: 'kmh'
        value_template:  "{{ ( (states.sensor.pws_wind_kph_2.state | float | round(1) ) + (states.sensor.pws_wind_gust_kph_2.state | float | round(1) ) ) / 2.0 }}"





    avgwindtotal:
        friendly_name: 'Avg Wind Total'
        icon_template: mdi:weather-windy
        unit_of_measurement: 'kmh'
        value_template:  "{{ (states.sensor.avg_wnd.state | float + states.sensor.avg_wnd_gust.state | float)/2.0 }}"



    amawindtotal:
        friendly_name: 'Exp Wind Total'
        icon_template: mdi:weather-windy
        unit_of_measurement: 'kmh'
        value_template:  "{{ ((states.sensor.ema_wind.state | float * 0.5 | round(1) ) + (states.sensor.ema_gust_wind.state | float * 0.7 | round(1) )) }}"



    expavgwindy:
        friendly_name: 'Exp Avg Wind'
        icon_template: mdi:weather-windy
        value_template: >-
         {% if ((states.sensor.ema_wind.state | float * 0.5 | round(1)) + (states.sensor.ema_gust_wind.state | float * 0.7) | round(1) ) > 18.0 -%}
            Windy
          {%- else -%}
            Beer
          {%- endif -%}


    avgwindy:
        friendly_name: 'Average Wind'
        icon_template: mdi:weather-windy
        value_template: >-
         {% if (states.sensor.avg_wnd.state | float + states.sensor.avg_wnd_gust.state | float)/2.0 > 18.0 -%}
            Windy
          {%- else -%}
            Beer
          {%- endif -%}


    windy:
        friendly_name: 'Current Wind'
        icon_template: mdi:weather-windy
        value_template: >-
         {% if (states.sensor.pws_wind_kph.state | float + states.sensor.pws_wind_gust_kph.state | float)/2.0 > 18.0 -%}
            Windy
          {%- else -%}
            Beer
          {%- endif -%}

    eveybody_home:
        friendly_name: 'Everyone Home'
        value_template: >-
          {% if is_state("device_tracker.dmitry", "home") and  is_state("device_tracker.eileen", "home") -%}
            everybody
          {% elif is_state("device_tracker.dmitry", "home") or  is_state("device_tracker.eileen", "home") -%}
            somebody
          {%- else -%}
            nobody
          {%- endif -%}

    dmitry_arriving:
        friendly_name: 'Dmitry Arriving'
        value_template: >-
          {%- if is_state('input_boolean.dmitry_arriving','on') -%}
            arriving
          {%- else -%}
            N/A
          {%- endif -%}

    eileen_arriving:
        friendly_name: 'Eileen Arriving'
        value_template: >-
          {%- if is_state('input_boolean.eileen_arriving','on') -%}
            arriving
          {%- else -%}
            N/A
          {%- endif -%}



    family_room_motion:
        friendly_name: 'Family Room Motion'
        value_template: >-
          {%- if is_state("sensor.family_room_window_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    family_room_window_open:
        friendly_name: 'Window'
        value_template: >-
          {%- if is_state("sensor.family_room_window_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.family_room_window_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}


    bedroom_motion:
        friendly_name: 'BedRoom Motion'
        #device_class: motion
        value_template: >-
          {%- if is_state("sensor.bedroom_multi_sensor_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}


    living_room_motion:
        friendly_name: 'Living Room Motion'
        #device_class: motion
        value_template: >-
          {%- if is_state("sensor.living_room_door_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    living_room_door_entry:
        friendly_name: 'Living Room Door'
        #device_class: opening
        value_template: >-
          {%- if is_state("sensor.living_room_door_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.living_room_door_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

    living_room_luminance:
        friendly_name: 'Living Room Luminance'
        #device_class: light
        value_template: >-
          {%- if is_state("sensor.living_room_door_luminance", "2") -%}
            Dark
          {%- else -%}
            Off
          {%- endif -%}

    office_motion:
        friendly_name: 'Office Motion'
        value_template: >-
          {%- if is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    kitchen_motion:
        friendly_name: 'Kitchen Motion'
        value_template: >-
          {%- if is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_burglar_2", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    office_door_open:
        friendly_name: 'Office Door'
        value_template: >-
          {%- if is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

    kitchen_door_open:
        friendly_name: 'Kitchen Door'
        value_template: >-
          {%- if is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control_2", "23") -%}
            Closed
          {%- elif is_state("sensor.philio_technology_corporation_pst02a_4_in_1_multisensor_access_control_2", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

