- platform: yr
  monitored_conditions:
    - windSpeed
    - windDirection

- platform: template
  sensors:

    bedroom_motion:
        friendly_name: 'BedRoom Motion'
        value_template: >-
          {%- if is_state("sensor.bedroom_multi_sensor_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}


    living_room_motion:
        friendly_name: 'Living Room Motion'
        value_template: >-
          {%- if is_state("sensor.living_room_door_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    living_room_door_entry:
        friendly_name: 'Living Room Door'
        value_template: >-
          {%- if is_state("sensor.living_room_door_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.living_room_door_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

    living_room_luminance:
        friendly_name: 'Living Room Luminance'
        value_template: >-
          {%- if is_state("sensor.living_room_door_luminance", "2") -%}
            Dark
          {%- else -%}
            Off
          {%- endif -%}

