- platform: yr
  monitored_conditions:
    - windSpeed
    - windDirection

- platform: template
  sensors:

    eveybody_home:
        friendly_name: 'Everyone Home'
        value_template: >-
          {% if is_state("device_tracker.dmitry", "home") and  is_state("device_tracker.eileen", "home") -%}
            everybody
          {% elif is_state("device_tracker.dmitry", "home") or  is_state("device_tracker.eileen", "home") -%}
            somebody
          {%- else -%}
            nobody
          {%- endif -%}


    dmitry_arriving:
        friendly_name: 'Dmitry Arriving'
        value_template: >-
          {%- if is_state('input_boolean.dmitry_arriving','on') -%}
            arriving
          {%- else -%}
            N/A
          {%- endif -%}

    eileen_arriving:
        friendly_name: 'Eileen Arriving'
        value_template: >-
          {%- if is_state('input_boolean.eileen_arriving','on') -%}
            arriving
          {%- else -%}
            N/A
          {%- endif -%}



    family_room_motion:
        friendly_name: 'Family Room Motion'
        value_template: >-
          {%- if is_state("sensor.family_room_window_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    family_room_window_open:
        friendly_name: 'Window'
        value_template: >-
          {%- if is_state("sensor.family_room_window_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.family_room_window_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}



    bedroom_motion:
        friendly_name: 'BedRoom Motion'
        value_template: >-
          {%- if is_state("sensor.bedroom_multi_sensor_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}


    living_room_motion:
        friendly_name: 'Living Room Motion'
        value_template: >-
          {%- if is_state("sensor.living_room_door_burglar", "8") -%}
            Burglar
          {%- else -%}
            Off
          {%- endif -%}

    living_room_door_entry:
        friendly_name: 'Living Room Door'
        value_template: >-
          {%- if is_state("sensor.living_room_door_access_control", "23") -%}
            Closed
          {%- elif is_state("sensor.living_room_door_access_control", "22") -%}
            Open
          {%- else -%}
            Unknown
          {%- endif -%}

    living_room_luminance:
        friendly_name: 'Living Room Luminance'
        value_template: >-
          {%- if is_state("sensor.living_room_door_luminance", "2") -%}
            Dark
          {%- else -%}
            Off
          {%- endif -%}


